#!/usr/bin/env bash
# oh-my-zsh, the managed shell rc block, and the default shell.
# shellcheck shell=bash

ZSHRC="$HOME/.zshrc"
BASHRC="$HOME/.bashrc"

install_omz() {
  step "oh-my-zsh"
  if [[ -d ${ZSH:-$HOME/.oh-my-zsh} ]]; then
    skip "oh-my-zsh already installed"
    return 0
  fi
  have zsh || { warn "zsh missing; skipping oh-my-zsh"; return 1; }

  local args=(--unattended)
  # First run: let oh-my-zsh lay down its template .zshrc. On re-runs keep ours.
  [[ -f $ZSHRC ]] && args+=(--keep-zshrc)

  RUNZSH=no CHSH=no \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" "${args[@]}" \
    && ok "oh-my-zsh installed" || warn "oh-my-zsh install failed"
}

# Does the rc file already init $1, outside our managed block?
_rc_has() {
  local file="$1" needle="$2"
  [[ -f $file ]] || return 1
  awk -v b="$BLOCK_BEGIN" -v e="$BLOCK_END" '
    $0 == b { inblock = 1; next } $0 == e { inblock = 0; next } !inblock { print }
  ' "$file" | grep -qF "$needle"
}

_rc_body() {
  local shell="$1" file="$2"

  cat <<'HEAD'
# Generated by dev-machine-config. Re-running the installer rewrites this
# block; put your own customisations outside of it.
export PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.atuin/bin" ] && export PATH="$HOME/.atuin/bin:$PATH"
export EDITOR="nvim"
export VISUAL="nvim"
HEAD

  cat <<'BREW'

# --- homebrew ---
for _brew in /home/linuxbrew/.linuxbrew/bin/brew "$HOME/.linuxbrew/bin/brew"; do
  [ -x "$_brew" ] && eval "$("$_brew" shellenv)" && break
done
unset _brew
BREW

  # mise owns the tool PATH and the [shell_alias] entries, so activate it after
  # PATH is set up but before anything that shadows it.
  cat <<MISE

# --- mise (tools, shell aliases) ---
if command -v mise >/dev/null 2>&1; then
  eval "\$(mise activate $shell)"
fi
MISE

  if ! _rc_has "$file" "atuin init"; then
    cat <<ATUIN

# --- atuin (shell history) ---
if command -v atuin >/dev/null 2>&1; then
  eval "\$(atuin init $shell)"
fi
ATUIN
  fi

  if ! _rc_has "$file" "zoxide init"; then
    cat <<ZOXIDE

# --- zoxide (smart jump: z / zi) ---
if command -v zoxide >/dev/null 2>&1; then
  eval "\$(zoxide init $shell)"
fi
ZOXIDE
  fi

  cat <<FZF

# --- fzf ---
if command -v fzf >/dev/null 2>&1; then
  if fzf --$shell >/dev/null 2>&1; then
    eval "\$(fzf --$shell)"
  else
    for _d in /usr/share/fzf /usr/share/doc/fzf/examples /usr/share/$shell/site-functions; do
      [ -f "\$_d/key-bindings.$shell" ] && . "\$_d/key-bindings.$shell"
      [ -f "\$_d/completion.$shell" ] && . "\$_d/completion.$shell"
    done
    unset _d
  fi
fi
FZF

  # Aliases come from mise's [shell_alias]; these are the ones mise can't express.
  cat <<'TAIL'

# --- misc ---
alias ll='eza --git -l -o --header --icons'
alias lt='eza --git --tree --level=2'
alias vim='nvim'
alias lg='lazygit'
TAIL
}

configure_shells() {
  step "Shell configuration"

  write_block "$ZSHRC" "$(_rc_body zsh "$ZSHRC")"
  ok "updated $ZSHRC"

  write_block "$BASHRC" "$(_rc_body bash "$BASHRC")"
  ok "updated $BASHRC"
}

set_default_shell() {
  step "Default shell"
  local zsh_path target_user current
  zsh_path="$(command -v zsh || true)"
  [[ -n $zsh_path ]] || { warn "zsh not found; leaving default shell alone"; return 1; }
  target_user="${SUDO_USER:-$(id -un)}"
  current="$(getent passwd "$target_user" 2>/dev/null | cut -d: -f7)"

  if [[ $current == "$zsh_path" ]]; then
    skip "default shell is already $zsh_path"
    return 0
  fi

  grep -qxF "$zsh_path" /etc/shells 2>/dev/null || \
    printf '%s\n' "$zsh_path" | $SUDO tee -a /etc/shells >/dev/null

  if $SUDO chsh -s "$zsh_path" "$target_user" 2>/dev/null; then
    ok "default shell for $target_user -> $zsh_path"
  else
    warn "could not change default shell; run: chsh -s $zsh_path"
  fi
}
